---
- name: Assert required variables for role are defined
  ansible.builtin.include_tasks:
    file: assert.yaml
    apply:
      delegate_to: localhost
      run_once: true

- name: Install mailutils
  ansible.builtin.package:
    name: mailutils
    state: present
  become: true

- name: Move failmail service and validate
  block:
    - name: Move failmail service to host
      ansible.builtin.template:
        src: failmail.service
        dest: /lib/systemd/system/failmail@.service
        # does not work using Ansible
        # validate: "systemd-analyze verify %s"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      become: true
      register: fail_mail_template

    - name: Validate failmail service
      # validation as separate task
      ansible.builtin.command: systemd-analyze verify failmail@.service
      args:
        chdir: "/lib/systemd/system"
      changed_when: false
      become: true
  notify: "reload systemd"
